name:                light2d-hs
version:             0.1.0.0
github:              "PragmaTwice/light2d-hs"
license:             BSD3
author:              "PragmaTwice"
maintainer:          "i@twice.moe"
copyright:           "(C) 2019 PragmaTwice"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PragmaTwice/light2d-hs#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels == 3.3.3
- bytestring == 0.10.8.2
- primitive == 0.6.4.0

library:
  source-dirs: src

executables:
  light2d-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - light2d-hs

tests:
  light2d-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - light2d-hs
